# Generated by Django 6.0.2 on 2026-07-01 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='annual_demand',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Annual demand cannot be negative.')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Current stock cannot be negative.')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='holding_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Holding cost cannot be negative.')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='ordering_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Ordering cost cannot be negative.')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='Selling price must be greater than 0.')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='Unit cost must be greater than 0.')]),
        ),
    ]
