# Generated by Django 6.0.2 on 2026-07-01 15:51

import catalog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_annual_demand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message="Name must start with a letter or number, and may only contain letters, numbers, spaces, and - _ . , ' & ( )", regex="^[A-Za-z0-9][A-Za-z0-9 \\-_.,'&()]*$"), catalog.models.validate_name_has_letter]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message="Name must start with a letter or number, and may only contain letters, numbers, spaces, and - _ . , ' & ( )", regex="^[A-Za-z0-9][A-Za-z0-9 \\-_.,'&()]*$"), catalog.models.validate_name_has_letter]),
        ),
    ]
