# Generated by Django 6.0.2 on 2026-07-01 16:45

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_point',
            field=models.PositiveIntegerField(default=10, help_text='Stock level at which this product should be flagged as low/reorder-needed.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', validators=[catalog.models.validate_image_upload_size]),
        ),
    ]
