# Generated by Django 6.0.2 on 2026-07-01 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_alter_purchaseitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (digits, spaces, hyphens, and an optional leading + only).', regex='^\\+?[0-9\\- ]{7,15}$')]),
        ),
    ]
