# Generated by Django 6.0.2 on 2026-05-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_customer_order_customer_orderreturn_orderstatuslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='buyer_pan',
            field=models.CharField(blank=True, max_length=20, verbose_name='PAN No.'),
        ),
    ]
