# Generated by Django 6.0.2 on 2026-07-01 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_invoice_discount_alter_orderitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='buyer_pan',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(message='PAN number must be exactly 9 digits.', regex='^\\d{9}$')], verbose_name='PAN No.'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (digits, spaces, hyphens, and an optional leading + only).', regex='^\\+?[0-9\\- ]{7,15}$')]),
        ),
    ]
