# Generated by Django 6.0.2 on 2026-07-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_customer_buyer_pan_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(blank=True, choices=[('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('WHATSAPP', 'WhatsApp'), ('FRIEND_FAMILY', 'Friend/Family'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
