# Generated by Django 6.0.2 on 2026-07-15 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_type',
            field=models.CharField(choices=[('AMOUNT', 'Amount (NPR)'), ('PERCENT', 'Percent (%)')], default='AMOUNT', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Discount cannot be negative.')]),
        ),
    ]
